name: build plugin

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - 'test/**'
      - '.run/**'
      - '.github/**'
      - 'docs/**'
      - 'coverage/**'
      - 'test/**'
      - '*.*'
      - '.*'
  schedule:
## https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule
##            ┌───────────── minute (0 - 59)
##            │ ┌───────────── hour (0 - 23)
##            │ │ ┌───────────── day of the month (1 - 31)
##            │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
##            │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
##            │ │ │ │ │
##            │ │ │ │ │
##            │ │ │ │ │
##            * * * * *
#    - cron: '* * 1 * *'
    - cron: '* 12 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 20
      - name: Set up Node.js + pnpm
        uses: pnpm/setup@v1
        with:
          version: next-12
          runtime: node@26
          cache: true
      - name: setup git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --local core.autocrlf false
          git config --local core.ignorecase false
          git config --local include.path ../.gitconfig
          git config --local core.autocrlf false
          git config --local core.ignorecase false
      - name: Fetch git tags
        run: |
          git fetch origin 'refs/tags/*:refs/tags/*' --depth=20
      - name: install deps
        run: |
          pnpm install --frozen-lockfile
          pnpm run ci:install
      - name: run ci:build
        if: success()
#        env:
        run: |
          pnpm run ci:build
      - name: run ci:postpublish
        if: success()
#        env:
        run: |
          pnpm run ci:postpublish
      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Tag
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
          force: true
