name: check test

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node.js + pnpm
        uses: pnpm/setup@v1
        with:
          version: next-12
          runtime: node@26
          cache: true
      - name: setup git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: install deps
        run: |
          pnpm install --frozen-lockfile
          pnpm run ci:install
      - name: run script
        if: success()
#        env:
        run: pnpm run ci:test
